spring:
  jpa:
    open-in-view: false
    database: MYSQL
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        globally_quoted_identifiers: true
        default_batch_fetch_size: 200
        hbm2ddl:
          auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org:
      springframework:
        transaction.interceptor: trace
        orm:
          jpa: DEBUG
      hibernate:
        orm:
          jdbc.bind: TRACE

---
spring.config.activate.on-profile:
  - default
  - dev
database:
  master:
    minimumIdle: 10
    maximumPoolSize: 30
    driverClassName: com.mysql.cj.jdbc.Driver
    auto-commit: false

  slave:
    minimumIdle: 10
    maximumPoolSize: 30
    driverClassName: com.mysql.cj.jdbc.Driver
    auto-commit: false
    read-only: true